steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/docker-images/next-js-app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/docker-images/next-js-app:$SHORT_SHA']
images: ['europe-central2-docker.pkg.dev/$PROJECT_ID/docker-images/next-js-app:$SHORT_SHA']

