steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/docker-images/next-js-app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/docker-images/next-js-app:$SHORT_SHA']
- name: 'gcr.io/google-cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'services'
    - 'update'
    - 'next-js-app'
    - '--region'
    - 'europe-central2'
    - '--image'
    - 'europe-central2-docker.pkg.dev/$PROJECT_ID/docker-images/next-js-app:$SHORT_SHA'
images: ['europe-central2-docker.pkg.dev/$PROJECT_ID/docker-images/next-js-app:$SHORT_SHA']

