steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=$${FIREBASE_API_KEY}' # <-- CRITICAL CHANGE HERE
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=gpc-connected.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=gpc-connected'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=gpc-connected.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=732854306302'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
    secretEnv:
      - 'FIREBASE_API_KEY' # This name must match the environment variable made available by secretEnv
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--set-secrets'
      - 'FIREBASE_SERVICE_ACCOUNT=firebase-service-account-key' # This assumes 'firebase-service-account-key' is the secret name in Secret Manager
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TRIGGER_ID: c11aad35-ef59-46e6-8352-c348e4a7836b
  _SERVICE_NAME: next-js-app
  _DEPLOY_REGION: europe-central2
  _AR_HOSTNAME: europe-central2-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: gpc-connected
  _PLATFORM: managed
  _FIREBASE_API_KEY: 'projects/$PROJECT_ID/secrets/firebase-api-key/versions/latest'
  _FIREBASE_SERVICE_ACCOUNT: 'projects/$PROJECT_ID/secrets/firebase-service-account-key/versions/latest' # This substitution is not directly used by --set-secrets, but can be helpful for clarity
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
secrets:
  - name: 'firebase-api-key'
    versionName: 'projects/$PROJECT_ID/secrets/firebase-api-key/versions/latest'
